'use client'

import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
import { useMemo, useRef, useState, useEffect } from 'react'
import { Line, useCursor, MeshDistortMaterial } from '@react-three/drei'
import { useRouter } from 'next/navigation'

export const Blob = ({ route = '/', ...props }) => {
  const router = useRouter()
  const [hovered, hover] = useState(false)
  useCursor(hovered)
  return (
    <mesh
      onClick={() => router.push(route)}
      onPointerOver={() => hover(true)}
      onPointerOut={() => hover(false)}
      {...props}
    >
      <sphereGeometry args={[1, 64, 64]} />
      <MeshDistortMaterial roughness={0.5} color={hovered ? 'hotpink' : '#1fb2f5'} />
    </mesh>
  )
}

export const Logo = ({ route = '/blob', ...props }) => {
  const mesh = useRef(null)
  const router = useRouter()

  const [hovered, hover] = useState(false)
  const points = useMemo(() => new THREE.EllipseCurve(0, 0, 3, 1.15, 0, 2 * Math.PI, false, 0).getPoints(100), [])

  useCursor(hovered)
  useFrame((state, delta) => {
    const t = state.clock.getElapsedTime()
    mesh.current.rotation.y = Math.sin(t) * (Math.PI / 8)
    mesh.current.rotation.x = Math.cos(t) * (Math.PI / 8)
    mesh.current.rotation.z -= delta / 4
  })

  return (
    <group ref={mesh} {...props}>
      {/* @ts-ignore */}
      <Line worldUnits points={points} color='#1fb2f5' lineWidth={0.15} />
      {/* @ts-ignore */}
      <Line worldUnits points={points} color='#1fb2f5' lineWidth={0.15} rotation={[0, 0, 1]} />
      {/* @ts-ignore */}
      <Line worldUnits points={points} color='#1fb2f5' lineWidth={0.15} rotation={[0, 0, -1]} />
      <mesh onClick={() => router.push(route)} onPointerOver={() => hover(true)} onPointerOut={() => hover(false)}>
        <sphereGeometry args={[0.55, 64, 64]} />
        <meshPhysicalMaterial roughness={0.5} color={hovered ? 'hotpink' : '#1fb2f5'} />
      </mesh>
    </group>
  )
}

export function Tape(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/TAPE.glb')
  const { actions } = useAnimations(animations, group)
  // useEffect(() => {
  //   if (actions) {
  //     actions['your_animation_name'].play(); // Replace 'your_animation_name' with the actual name of your animation
  //   }
  // }, [actions]);

  useEffect(() => {
    // console.log(actions); // Log the actions object to find animation names
    if (actions) {
      const animationNames = Object.keys(actions)
      console.log('Animations List', animationNames) // Log the actions object to find animation names

      if (animationNames.length > 0) {
        actions[animationNames[2]].play() // Play the first available animation
      }
    }
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group name='TCD5_body'>
          <mesh
            name='polySurface1'
            castShadow
            receiveShadow
            geometry={nodes.polySurface1.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface13'
            castShadow
            receiveShadow
            geometry={nodes.polySurface13.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface14'
            castShadow
            receiveShadow
            geometry={nodes.polySurface14.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface15'
            castShadow
            receiveShadow
            geometry={nodes.polySurface15.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface16'
            castShadow
            receiveShadow
            geometry={nodes.polySurface16.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface17'
            castShadow
            receiveShadow
            geometry={nodes.polySurface17.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface20'
            castShadow
            receiveShadow
            geometry={nodes.polySurface20.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface21'
            castShadow
            receiveShadow
            geometry={nodes.polySurface21.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface22'
            castShadow
            receiveShadow
            geometry={nodes.polySurface22.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface23'
            castShadow
            receiveShadow
            geometry={nodes.polySurface23.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface24'
            castShadow
            receiveShadow
            geometry={nodes.polySurface24.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface25'
            castShadow
            receiveShadow
            geometry={nodes.polySurface25.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface5'
            castShadow
            receiveShadow
            geometry={nodes.polySurface5.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface510'
            castShadow
            receiveShadow
            geometry={nodes.polySurface510.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface511'
            castShadow
            receiveShadow
            geometry={nodes.polySurface511.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface512'
            castShadow
            receiveShadow
            geometry={nodes.polySurface512.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface513'
            castShadow
            receiveShadow
            geometry={nodes.polySurface513.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface514'
            castShadow
            receiveShadow
            geometry={nodes.polySurface514.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface515'
            castShadow
            receiveShadow
            geometry={nodes.polySurface515.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface517'
            castShadow
            receiveShadow
            geometry={nodes.polySurface517.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface518'
            castShadow
            receiveShadow
            geometry={nodes.polySurface518.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface519'
            castShadow
            receiveShadow
            geometry={nodes.polySurface519.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface520'
            castShadow
            receiveShadow
            geometry={nodes.polySurface520.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface521'
            castShadow
            receiveShadow
            geometry={nodes.polySurface521.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface522'
            castShadow
            receiveShadow
            geometry={nodes.polySurface522.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface523'
            castShadow
            receiveShadow
            geometry={nodes.polySurface523.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface524'
            castShadow
            receiveShadow
            geometry={nodes.polySurface524.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface525'
            castShadow
            receiveShadow
            geometry={nodes.polySurface525.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface526'
            castShadow
            receiveShadow
            geometry={nodes.polySurface526.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface527'
            castShadow
            receiveShadow
            geometry={nodes.polySurface527.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface528'
            castShadow
            receiveShadow
            geometry={nodes.polySurface528.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface529'
            castShadow
            receiveShadow
            geometry={nodes.polySurface529.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface530'
            castShadow
            receiveShadow
            geometry={nodes.polySurface530.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface531'
            castShadow
            receiveShadow
            geometry={nodes.polySurface531.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface532'
            castShadow
            receiveShadow
            geometry={nodes.polySurface532.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface533'
            castShadow
            receiveShadow
            geometry={nodes.polySurface533.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface534'
            castShadow
            receiveShadow
            geometry={nodes.polySurface534.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface535'
            castShadow
            receiveShadow
            geometry={nodes.polySurface535.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface536'
            castShadow
            receiveShadow
            geometry={nodes.polySurface536.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface537'
            castShadow
            receiveShadow
            geometry={nodes.polySurface537.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface538'
            castShadow
            receiveShadow
            geometry={nodes.polySurface538.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface539'
            castShadow
            receiveShadow
            geometry={nodes.polySurface539.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface540'
            castShadow
            receiveShadow
            geometry={nodes.polySurface540.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface541'
            castShadow
            receiveShadow
            geometry={nodes.polySurface541.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface542'
            castShadow
            receiveShadow
            geometry={nodes.polySurface542.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface543'
            castShadow
            receiveShadow
            geometry={nodes.polySurface543.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface544'
            castShadow
            receiveShadow
            geometry={nodes.polySurface544.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface545'
            castShadow
            receiveShadow
            geometry={nodes.polySurface545.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface546'
            castShadow
            receiveShadow
            geometry={nodes.polySurface546.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface547'
            castShadow
            receiveShadow
            geometry={nodes.polySurface547.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface548'
            castShadow
            receiveShadow
            geometry={nodes.polySurface548.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface549'
            castShadow
            receiveShadow
            geometry={nodes.polySurface549.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface550'
            castShadow
            receiveShadow
            geometry={nodes.polySurface550.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface551'
            castShadow
            receiveShadow
            geometry={nodes.polySurface551.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface552'
            castShadow
            receiveShadow
            geometry={nodes.polySurface552.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface553'
            castShadow
            receiveShadow
            geometry={nodes.polySurface553.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface554'
            castShadow
            receiveShadow
            geometry={nodes.polySurface554.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface555'
            castShadow
            receiveShadow
            geometry={nodes.polySurface555.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface556'
            castShadow
            receiveShadow
            geometry={nodes.polySurface556.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface557'
            castShadow
            receiveShadow
            geometry={nodes.polySurface557.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface558'
            castShadow
            receiveShadow
            geometry={nodes.polySurface558.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface559'
            castShadow
            receiveShadow
            geometry={nodes.polySurface559.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface561'
            castShadow
            receiveShadow
            geometry={nodes.polySurface561.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface562'
            castShadow
            receiveShadow
            geometry={nodes.polySurface562.geometry}
            material={materials.sony}
          />
          <group name='polySurface563' />
          <group name='polySurface564' />
          <group name='polySurface565' />
          <group name='polySurface566' />
          <mesh
            name='polySurface567'
            castShadow
            receiveShadow
            geometry={nodes.polySurface567.geometry}
            material={materials.sony}
          />
          <group name='polySurface568' position={[-0.84, 0.394, 0.684]} />
          <group name='polySurface569' />
          <mesh
            name='polySurface570'
            castShadow
            receiveShadow
            geometry={nodes.polySurface570.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface571'
            castShadow
            receiveShadow
            geometry={nodes.polySurface571.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface572'
            castShadow
            receiveShadow
            geometry={nodes.polySurface572.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface573'
            castShadow
            receiveShadow
            geometry={nodes.polySurface573.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface574'
            castShadow
            receiveShadow
            geometry={nodes.polySurface574.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface575'
            castShadow
            receiveShadow
            geometry={nodes.polySurface575.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface576'
            castShadow
            receiveShadow
            geometry={nodes.polySurface576.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface577'
            castShadow
            receiveShadow
            geometry={nodes.polySurface577.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface578'
            castShadow
            receiveShadow
            geometry={nodes.polySurface578.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface579'
            castShadow
            receiveShadow
            geometry={nodes.polySurface579.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface580'
            castShadow
            receiveShadow
            geometry={nodes.polySurface580.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface581'
            castShadow
            receiveShadow
            geometry={nodes.polySurface581.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface582'
            castShadow
            receiveShadow
            geometry={nodes.polySurface582.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface583'
            castShadow
            receiveShadow
            geometry={nodes.polySurface583.geometry}
            material={materials.sony}
            position={[0, 0, -0.004]}
          />
          <mesh
            name='polySurface6'
            castShadow
            receiveShadow
            geometry={nodes.polySurface6.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface601'
            castShadow
            receiveShadow
            geometry={nodes.polySurface601.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface606'
            castShadow
            receiveShadow
            geometry={nodes.polySurface606.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface607'
            castShadow
            receiveShadow
            geometry={nodes.polySurface607.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface609'
            castShadow
            receiveShadow
            geometry={nodes.polySurface609.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface610'
            castShadow
            receiveShadow
            geometry={nodes.polySurface610.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface611'
            castShadow
            receiveShadow
            geometry={nodes.polySurface611.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface612'
            castShadow
            receiveShadow
            geometry={nodes.polySurface612.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface613'
            castShadow
            receiveShadow
            geometry={nodes.polySurface613.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface614'
            castShadow
            receiveShadow
            geometry={nodes.polySurface614.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface615'
            castShadow
            receiveShadow
            geometry={nodes.polySurface615.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface616'
            castShadow
            receiveShadow
            geometry={nodes.polySurface616.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface617'
            castShadow
            receiveShadow
            geometry={nodes.polySurface617.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface618'
            castShadow
            receiveShadow
            geometry={nodes.polySurface618.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface619'
            castShadow
            receiveShadow
            geometry={nodes.polySurface619.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface620'
            castShadow
            receiveShadow
            geometry={nodes.polySurface620.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface621'
            castShadow
            receiveShadow
            geometry={nodes.polySurface621.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface622'
            castShadow
            receiveShadow
            geometry={nodes.polySurface622.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface623'
            castShadow
            receiveShadow
            geometry={nodes.polySurface623.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface624'
            castShadow
            receiveShadow
            geometry={nodes.polySurface624.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface625'
            castShadow
            receiveShadow
            geometry={nodes.polySurface625.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface626'
            castShadow
            receiveShadow
            geometry={nodes.polySurface626.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface627'
            castShadow
            receiveShadow
            geometry={nodes.polySurface627.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface628'
            castShadow
            receiveShadow
            geometry={nodes.polySurface628.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface629'
            castShadow
            receiveShadow
            geometry={nodes.polySurface629.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface630'
            castShadow
            receiveShadow
            geometry={nodes.polySurface630.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface631'
            castShadow
            receiveShadow
            geometry={nodes.polySurface631.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface632'
            castShadow
            receiveShadow
            geometry={nodes.polySurface632.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface633'
            castShadow
            receiveShadow
            geometry={nodes.polySurface633.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface634'
            castShadow
            receiveShadow
            geometry={nodes.polySurface634.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface642'
            castShadow
            receiveShadow
            geometry={nodes.polySurface642.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface643'
            castShadow
            receiveShadow
            geometry={nodes.polySurface643.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface645'
            castShadow
            receiveShadow
            geometry={nodes.polySurface645.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface646'
            castShadow
            receiveShadow
            geometry={nodes.polySurface646.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface647'
            castShadow
            receiveShadow
            geometry={nodes.polySurface647.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface668'
            castShadow
            receiveShadow
            geometry={nodes.polySurface668.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface669'
            castShadow
            receiveShadow
            geometry={nodes.polySurface669.geometry}
            material={materials.sony}
          />
        </group>
        <group name='TCD5_cover' position={[-0.043, 0.047, -0.048]} rotation={[-1.361, 0, 0]}>
          <mesh
            name='polySurface648'
            castShadow
            receiveShadow
            geometry={nodes.polySurface648.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface649'
            castShadow
            receiveShadow
            geometry={nodes.polySurface649.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface650'
            castShadow
            receiveShadow
            geometry={nodes.polySurface650.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface651'
            castShadow
            receiveShadow
            geometry={nodes.polySurface651.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface652'
            castShadow
            receiveShadow
            geometry={nodes.polySurface652.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface653'
            castShadow
            receiveShadow
            geometry={nodes.polySurface653.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface654'
            castShadow
            receiveShadow
            geometry={nodes.polySurface654.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface655'
            castShadow
            receiveShadow
            geometry={nodes.polySurface655.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface656'
            castShadow
            receiveShadow
            geometry={nodes.polySurface656.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface658'
            castShadow
            receiveShadow
            geometry={nodes.polySurface658.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface659'
            castShadow
            receiveShadow
            geometry={nodes.polySurface659.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface660'
            castShadow
            receiveShadow
            geometry={nodes.polySurface660.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface661'
            castShadow
            receiveShadow
            geometry={nodes.polySurface661.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface662'
            castShadow
            receiveShadow
            geometry={nodes.polySurface662.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface663'
            castShadow
            receiveShadow
            geometry={nodes.polySurface663.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface664'
            castShadow
            receiveShadow
            geometry={nodes.polySurface664.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface665'
            castShadow
            receiveShadow
            geometry={nodes.polySurface665.geometry}
            material={materials.sony}
          />
          <mesh
            name='polySurface666'
            castShadow
            receiveShadow
            geometry={nodes.polySurface666.geometry}
            material={materials.sony}
          />
        </group>
        <mesh
          name='rolll'
          castShadow
          receiveShadow
          geometry={nodes.rolll.geometry}
          material={materials.CassetteTape_01a1}
          position={[0, 0.017, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <group name='ff' position={[-0.025, 0.035, 0.062]}>
          <mesh
            name='polySurface563001'
            castShadow
            receiveShadow
            geometry={nodes.polySurface563001.geometry}
            material={materials.sony}
            position={[0.025, -0.035, -0.062]}
          />
        </group>
        <group name='PAuse' position={[0.016, 0.038, 0.058]}>
          <mesh
            name='polySurface565001'
            castShadow
            receiveShadow
            geometry={nodes.polySurface565001.geometry}
            material={materials.sony}
            position={[-0.016, -0.038, -0.058]}
          />
        </group>
        <group name='PLAy' position={[-0.045, 0.035, 0.061]}>
          <mesh
            name='polySurface564001'
            castShadow
            receiveShadow
            geometry={nodes.polySurface564001.geometry}
            material={materials.sony}
            position={[0.045, -0.035, -0.061]}
          />
        </group>
        <group name='Record' position={[-0.008, 0.039, 0.06]}>
          <mesh
            name='polySurface566001'
            castShadow
            receiveShadow
            geometry={nodes.polySurface566001.geometry}
            material={materials.sony}
            position={[0.008, -0.039, -0.06]}
          />
        </group>
        <group name='rew' position={[-0.086, 0.039, 0.059]}>
          <mesh
            name='polySurface568001'
            castShadow
            receiveShadow
            geometry={nodes.polySurface568001.geometry}
            material={materials.sony}
            position={[0.002, 0, 0.01]}
          />
        </group>
        <group name='Stop' position={[-0.066, 0.036, 0.055]}>
          <mesh
            name='polySurface569001'
            castShadow
            receiveShadow
            geometry={nodes.polySurface569001.geometry}
            material={materials.sony}
            position={[0.066, -0.036, -0.055]}
          />
        </group>
        <mesh
          name='CassetteTape_Main_low_01_2001'
          castShadow
          receiveShadow
          geometry={nodes.CassetteTape_Main_low_01_2001.geometry}
          material={materials.CassetteTape_01a1}
          position={[-0.006, 0.059, -0.003]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name='rolll001'
          castShadow
          receiveShadow
          geometry={nodes.rolll001.geometry}
          material={materials.CassetteTape_01a1}
          position={[-0.049, 0.058, -0.003]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
      </group>
    </group>
  )
}
